LangLearnWebsite/urls.py
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import include, path
from learner import views as app_views

from .views import redirect_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('learner/', include('learner.urls')),
    path('', redirect_view),
]

learner/urls.py
from django.urls import path

from . import views

app_name = "learner"
urlpatterns = [
    path('', views.index, name='index'),
	path('join', views.join, name= "join"),
    path('login', views.user_login, name = "login"),
    path('logout', views.user_logout, name = "logout"),
    path('dashboard', views.dash, name = "dashboard"),
    path('deck/add', views.deck_add, name='deckAdd'),
    path('card/add/<int:deckId>', views.card_add, name = "cardAdd"),
    path('deck/<int:deckId>', views.deck_review, name='deckReview'),
    path('deck/<int:deckId>/answer', views.card_answer, name='answer'),
    path('deck/<int:deckId>/delete', views.deck_delete, name = 'deckDelete'),
]

learner/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Deck(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	weight = models.DecimalField(max_digits=5, decimal_places=4)
	name = models.CharField(max_length=100, unique = True)
	description = models.CharField(max_length=700)


class Card(models.Model):
	deck = models.ForeignKey(Deck, on_delete=models.CASCADE)
	question = models.CharField(max_length=100)
	answer = models.CharField(max_length=100)
	weight = models.DecimalField(max_digits=5, decimal_places=4)
	sentence = models.CharField(max_length=700)
	lastUpdatedDate = models.DateTimeField(auto_now=True, auto_now_add=False)
	

learner/forms.py
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm
from .models import Deck, Card


class DeckForm(ModelForm):
	class Meta:
		model=Deck
		fields = ['name', 'description']
		
class CardForm(ModelForm):
	class Meta:
		model = Card
		fields = ['question', 'answer', 'sentence']

class JoinForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'size': '30'}))
    class Meta():
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')
        help_texts = {'username': None}

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())
    

learner/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.http import Http404
from .forms import JoinForm, LoginForm, CardForm, DeckForm
from .models import Deck, Card
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import decimal
from django.utils import timezone

# Create your views here.

def index(request):
    return render(request, "index.html")

@login_required(login_url='learner:login') 
def dash(request):
	if request.user.is_authenticated:
		use = request.user
		decks = Deck.objects.filter(user = use)
		if(len(decks) < 1):
			pass
		else:
			#decay card weights based on amount of time that has passed
			now = timezone.now()
			for deck in decks:
				cards = Card.objects.filter(deck = deck)
				if(len(cards) < 1):
					continue
				for card in cards:
					num = decimal.Decimal(0.2)
					null = decimal.Decimal(0.0)
					dateArith = now - card.lastUpdatedDate
					hours = dateArith.seconds / 60 / 60
					if(hours < 24):
						continue
					while hours >= 24:
						card.weight = card.weight - num
						hours = hours - 24
					if(card.weight < null):
						card,weight = null
					#saving will automatically update the date to the present date
					card.save()
			
			
			#update deck weights
			for deck in decks:
				num = decimal.Decimal(0.0)
				cards = Card.objects.filter(deck = deck)
				if(len(cards) < 1):
					continue
				for card in cards:
					num = num + card.weight
				lengthh = decimal.Decimal(len(cards))
				deck.weight = (num/lengthh)
				deck.save()
		context = {
			"decks" : decks
		}
		return render(request, "dashboard.html", context)
	else:
		return redirect('learner:index')

@login_required(login_url='learner:login')		
def deck_delete(request, deckId):
	deck = Deck.objects.get(id=deckId)
	deck.delete()
	return redirect('learner:dashboard')
	
@login_required(login_url='learner:login')
def deck_add(request):
	if (request.method == "POST"):
		if ("add" in request.POST):
			add_form = DeckForm(request.POST)
			if (add_form.is_valid()):
				description = add_form.cleaned_data["description"]
				dName = add_form.cleaned_data["name"]
				user = User.objects.get(id=request.user.id)
				Deck(user=user, description=description, name=dName, weight=0.1).save()
				return redirect("learner:dashboard")
			else:
				context = {
					"form_data": add_form
				}
				return render(request, 'deckAdd.html', context)
		else:
		# Cancel
			return redirect("learner:dashboard")
	else:
		context = {
			"form_data": DeckForm()
		}
		return render(request, 'deckAdd.html', context)

@login_required(login_url='learner:login')
def card_add(request, deckId):
	if (request.method == "POST"):
		if ("add" in request.POST):
			add_form = CardForm(request.POST)
			if (add_form.is_valid()):
				deck = Deck.objects.get(id=deckId)
				question = add_form.cleaned_data["question"]
				answer = add_form.cleaned_data["answer"]
				sentence = add_form.cleaned_data["sentence"]
				Card(deck=deck, question=question, answer=answer, weight=0.1, sentence=sentence).save()
				return redirect("learner:dashboard")
			else:
				context = {
					"form_data": add_form
				}
				return render(request, 'cardAdd.html', context)
		else:
		# Cancel
			return redirect("learner:dashboard")
	else:
		context = {
			"form_data": CardForm()
		}
		return render(request, 'cardAdd.html', context)
		
@login_required(login_url='learner:login')
def deck_review(request, deckId):
	deck = Deck.objects.get(id = deckId)
	cDB = Card.objects.filter(deck=deck)
	cards = sorted(cDB, key = lambda x: x.weight)
	#check sorted length
	if(len(cards) < 1):
		return redirect("learner:dashboard")
	if(cards[0].weight != 1.0):
		context = {
			"deck": deck,
			"card": cards[0]
		}
		return render(request, 'reviewDeck.html', context)
	else:
		return redirect("learner:dashboard")

@login_required(login_url='learner:login')
def card_answer(request, deckId):
	deck = Deck.objects.get(id = deckId)
	cDB = Card.objects.filter(deck=deck)
	currentCard = sorted(cDB, key = lambda x: x.weight)[0]
	if (request.method == "POST"): 
		if ("great" in request.POST):
			d= decimal.Decimal(0.4)
			currentCard.weight = currentCard.weight + d
		if ("good" in request.POST):
			d= decimal.Decimal(0.2)
			currentCard.weight = currentCard.weight + d
		if ("neutral" in request.POST):
			d= decimal.Decimal(0.1)
			currentCard.weight = currentCard.weight + d
		if ("bad" in request.POST):
			d= decimal.Decimal(0.1)
			currentCard.weight = currentCard.weight - d
		if ("terrible" in request.POST):
			d= decimal.Decimal(0.2)
			currentCard.weight = currentCard.weight - d
			
		if(currentCard.weight > 1.0):
			currentCard.weight = 1.0
		if(currentCard.weight < 0.0):
			currentCard.weight = 0.0
		currentCard.save()
		return redirect("learner:deckReview", deckId = deckId)

	else:
		context = {
			"deck": deck,
			"card": currentCard
		}
		return render(request, "cardAnswer.html", context)
def join(request):
    if (request.method == "POST"):
        join_form = JoinForm(request.POST)
        if (join_form.is_valid()):
            # Save form data to DB
            user = join_form.save()
            # Encrypt the password
            user.set_password(user.password)
            # Save encrypted password to DB
            user.save()
            # Success! Redirect to home page.
            return redirect("learner:index")
        else:
            # Form invalid, print errors to console
            context = {"join_form": join_form}
            return render(request, 'join.html', context)
    else:
        join_form = JoinForm()
        page_data = {"join_form": join_form}
        return render(request, 'join.html', page_data)


def user_login(request):

    if (request.method == 'POST'):
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            # First get the username and password supplied
            username = login_form.cleaned_data["username"]
            password = login_form.cleaned_data["password"]
            # Django's built-in authentication function:
            user = authenticate(username=username, password=password)
            # If we have a user
            if user:
                # Check it the account is active
                if user.is_active:
                    # Log the user in.
                    login(request, user)
                    # Send the user back to homepage
                    return redirect("/")
                else:
                    # If account is not active:
                    return HttpResponse("Your account is not active.")
            else:
                print("Someone tried to login and failed.")
                print("They used username: {} and password: {}".format(
                    username, password))
                return render(request, 'login.html', {"login_form": LoginForm})
    else:
        # Nothing has been provided for username or password.
        return render(request, 'login.html', {"login_form": LoginForm})


def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return redirect('learner:login')

learner/templates/bootstrap.html
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

learner/templates/cardAdd.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <title>New Card</title>
    {% include "bootstrap.html" %}
    <style>
		body {
				background-color: #a8aaad;
			}
    </style>
</head>

<body>
    {% include "navbar.html" %}
    <div class="jumbotron" style="background-color: #0c2245; color: white;" >
        <h1>Create New Card</h1>
        <form method="POST">
            {% csrf_token %}
            <table>
                {{ form_data.as_table }}
                <tr>
                    <td></td>
                    <td>
                        <a href="{% url 'learner:dashboard' %}" class="btn btn-secondary">Cancel</a>
                        <input type="submit" class="btn btn-primary" name="add" value="Create Card">
                    </td>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</body>

</html>

learner/templates/cardAnswer.html
<!DOCTYPE html>
<html>
<head>
    {% include "bootstrap.html" %}
    <style>
    .container {
		margin: auto;
		position: absolute;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		  text-align: center;
	}
	
	body {
			background-color: #a8aaad;
		}
    
    </style>
</head>

<body>
	{% include "navbar.html" %}

    <div class="container">
        <div style="background-color: #0c2245; color: white;" class="jumbotron">
            <h1>{{ card.answer }} </h1>
            <br>
            <h3>{{ card.sentence }} </h3>
            <br>
            <p>How do you feel about your knowledge of this card?</p>
            <form method="POST">
				{% csrf_token %}
				<input type="submit" class="btn btn-secondary" name="great" value = "Great">
				<input type="submit" class="btn btn-secondary" name="good" value = "Good">
				<input type="submit" class="btn btn-secondary" name="neutral" value = "Neutral">
				<input type="submit" class="btn btn-secondary" name="bad" value = "Bad">
				<input type="submit" class="btn btn-secondary" name="terrible" value = "Terrible">            
			</form>
        </div>
    </div>


</body>

</html>

learner/templates/dashboard.html
<!DOCTYPE html>
<!--Dashboard, displays all decks into bootstrap cards in the bootstrap grid-->
<html>

<head>
	{% include "bootstrap.html" %}
	<!-- load static -->
	<!--link rel="stylesheet" href="static 'common.css' "/-->
	<style>
		body {
			background-color: #a8aaad;
		}

		.card {
			background-color: #0c2245;
			color: white;
		}

		.row {
			padding: 1em;
			display: flex;
			flex-wrap: wrap;
			justify-content:left;
			gap: 1em;
			background-color: #343a40;
		}
		#buttonHolder{
			display: flex;
			justify-content: center;
			align-items: center;
		}
	</style>
</head>

<body>
	{% include "navbar.html" %}
	<br>
	<div id="buttonHolder">
		<a href="{% url 'learner:deckAdd' %}" class="btn btn-dark" style="margin-bottom: 1em;">Create New Deck</a>
	</div>
	{% if not decks %}
	<p>There are no decks to display, try creating one!</p>
	{% else %}
	<div class="row">
		{% for row in decks %}


		<div class="card" style="width: 18rem;">
			<div class="card-body">
				<h5 class="card-title">{{ row.name }} </h5>
				<h6 class="card-subtitle mb-2 text-muted">{{ row.weight }}</h6>
				<p>{{ row.description }}</p>
				<a href="{% url 'learner:cardAdd' row.id %}" class="card-link">Add Card</a>
				<a href="{% url 'learner:deckDelete' row.id %}" class="card-link">Delete Deck</a>
				<a href="{% url 'learner:deckReview' row.id %}" class="card-link">Review Deck</a>
			</div>
		</div>


		{% endfor %}
	</div>

	{% endif %}

	<script>
		var weights = document.getElementsByClassName("card-subtitle mb-2 text-muted");
		console.log(parseFloat(weights[0].innerHTML));
		for (let i = 0; i < weights.length; i++) {
			weight = parseFloat(weights[i].innerHTML)
			if (weight <= .6) {
				weights[i].innerHTML = '<p style="color: yellow;">Urgency:Medium</p>'
			}
			if (weight < .3) {
				weights[i].innerHTML = '<p style="color: red;">Urgency:High</p>'
			}
			if (weight > .6) {
				weights[i].innerHTML = '<p style="color: green;">Urgency:Low</p>'
			}
		}
	</script>
</body>

</html>

learner/templates/deckAdd.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <title>New Deck</title>
    {% include "bootstrap.html" %}
    <style>
		body {
				background-color: #a8aaad;
			}
    </style>
</head>

<body>
    {% include "navbar.html" %}
    <div class="jumbotron" style="background-color: #0c2245; color: white;" >
        <h1>Create New Deck</h1>
        <form method="POST">
            {% csrf_token %}
            <table>
                {{ form_data.as_table }}
                <tr>
                    <td></td>
                    <td>
                        <a href="{% url 'learner:dashboard' %}" class="btn btn-secondary">Cancel</a>
                        <input type="submit" class="btn btn-primary" name="add" value="Create Deck">
                    </td>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</body>

</html>

learner/templates/index.html
 <!DOCTYPE html>
 <html>
<head>
    {% load static %}
    <!--link rel="stylesheet" href="static 'common.css' " /-->
    {% include "bootstrap.html" %}
	<style>
		.card {
				background-color: #0c2245; 
				color: white;
		}
		.jumbotron {
			background-color:#0c2245; color:white;
		}
		body {
				background-color: #a8aaad;
		}
		

	</style>
</head>

	{% include "navbar.html" %}
<body>
<div class="jumbotron" style="text-align:center;">
  <h1 class="display-4" >Lingo</h1>
  <p class="lead">A Flashcard Application that keeps track of what you need to learn</p>
  </p>
</div>

<div id="accordion" >
  <div class="card">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0">
        <button class="btn btn-outline-light" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          What it is:
        </button>
      </h5>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
      <div class="card-body">
        Lingo is a flashcard application which will strive to keep you on top of what you need to review. Create your own decks of material and Lingo will keep a score of your knowledge levels for these decks. Your knowledge level will decay over time, and you will be able to see which decks are in most need of review!
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingTwo">
      <h5 class="mb-0">
        <button class="btn btn-outline-light collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          How it works:
        </button>
      </h5>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
      <div class="card-body">
		  To start off, you need to create a deck. You then can create cards for this deck. Fill the cards with your question(what you would see on the front side of the card) an answer that you want to associate to this card and an optional example sentence you would like to see with the question.
		  Your Dashboard will display all of your created decks, and the urgency with which they must be reviewed. Click on the deck to review it.
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingThree">
      <h5 class="mb-0">
        <button class="btn btn-outline-light collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Get started:
        </button>
      </h5>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
      <div class="card-body">
		  First, <a href="{% url 'learner:join' %}">create an account</a>, after you are logged in, you can start by <a href="{% url 'learner:deckAdd' %}">creating a deck</a>
      </div>
    </div>
  </div>
</div>
</body>
</html>

learner/templates/join.html
<!DOCTYPE html>
<html>

<head>
    {% include "bootstrap.html" %}
    <style>
		body {
				background-color: #a8aaad;
			}
    </style>
</head>

<body>
    {% include "navbar.html" %}
    <div class="container">
        <div style="background-color: #0c2245; color: white;" class="jumbotron">
            <h1>Join</h1>
            <form method="POST">{% csrf_token %}
				<table>{{ join_form.as_table }}
					<tr>
                        <td><input type="submit" class="btn btn-primary" value="Join" /></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</body>

</html>

learner/templates/login.html
<!DOCTYPE html>
<html>
<head>
    {% include "bootstrap.html" %}
    <style>
		body {
				background-color: #a8aaad;
		}
    </style>

</head>

<body>
    {% include "navbar.html" %}

    <div class="container">
        <div style="background-color: #0c2245; color: white;" class="jumbotron">
            <h1>Login</h1>
            <form action="{% url 'learner:login' %}" method="POST">{% csrf_token %}
                <table>{{ login_form.as_table }}
                    <tr>
                        <td><input type="submit" class="btn btn-primary" value="Login" /></td>
                    </tr>
                    <tr>
                        <td>Click <a href="{% url 'learner:join' %}">here</a> to join.</td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</body>
</html>

learner/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light"  style="background-color:#a8aaad !important; color:white !important; border: 1px black !important;">
    <a class="navbar-brand" href="{% url 'learner:dashboard' %}">Lingo</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'learner:index' %}">Home <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link" href="{% url 'learner:dashboard' %}">Dashboard</a>
        {% if user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'learner:logout' %}">Logout</a>
        {% else %}
        <a class="nav-item nav-link" href="{% url 'learner:login' %}">Login</a>
        {% endif %}
      </div>
    </div>
  </nav>

learner/templates/reviewDeck.html
<!DOCTYPE html>
<html>
<head>
    {% include "bootstrap.html" %}
    <style>
    .container {
		margin: auto;
		position: absolute;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		  text-align: center;
	}
	
	body {
			background-color: #a8aaad;
		}
    
    </style>
</head>

<body>
	{% include "navbar.html" %}

    <div class="container">
        <div style="background-color: #0c2245; color: white;" class="jumbotron">
            <h1>{{ card.question }} </h1>
            <br>
            <br>
            <a class="btn btn-secondary" href="{% url 'learner:answer' deck.id %}" role="button">See Answer</a>
        </div>
    </div>


</body>

</html>